name: Trivy Vulnerability Scan

on:
  workflow_dispatch: # Ручной запуск
  schedule:
    - cron: '0 0 * * 0' # Еженедельный запуск ( воскресенье )

jobs:
  scan:
    name: Scan Docker Image with Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Trivy container image scan
        run: |
          trivy --severity=HIGH --format=json --output trivy-report.json ${{ inputs.image-ref }}
          if [ $? -ne 0 ]; then
            echo "High vulnerabilities found. Exiting with error."
            exit 1
          fi
        env:
          image-ref: alpine/openssl